"""real_username column to store real username

Revision ID: 2141863db566
Revises: 3731f944ce34
Create Date: 2025-08-05 13:46:35.165612

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2141863db566"
down_revision: Union[str, Sequence[str], None] = "3731f944ce34"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "solutions", sa.Column("real_username", sa.String(), nullable=True)
    )

    op.execute("""
        UPDATE solutions
        SET real_username=CASE
            WHEN user_name LIKE '@%' THEN user_name
            ELSE '@Iamer8'
        END
    """)

    op.alter_column("solutions", "real_username", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("solutions", "real_username")
    # ### end Alembic commands ###
